version: "3.9"
services:
  spring-api-gateway-template:
    build: .
    container_name: spring-api-gateway-template
    ports:
      - "80:80"
    env_file: .docker.env
    networks:
      - redis_network
      - jaeger_network
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- --no-check-certificate http://localhost/actuator/health || exit 1" ]
    deploy:
      resources:
        reservations:
          memory: 512M
          cpus: "0.25"
        limits:
          memory: 512M
          cpus: "0.25"

networks:
  redis_network:
    name: redis_network
    external: true
  jaeger_network:
    name: jaeger_network
    external: true
