auth:
  audience: https://localhost
  issuer: http://localhost

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
  data:
    redis:
      ssl:
        enabled: false
