auth:
  audience: http://leijendary.com
  issuer: http://iam.leijendary.com
  jwkSetUri: http://iam.leijendary.local/api/v1/.well-known/jwks.json

springdoc:
  apiDocs:
    enabled: false
  swaggerUi:
    enabled: false
