auth:
  audience: https://leijendary.com
  jwkSetUri: http://authentication.production:8443/authentication/api/v1/.well-known/jwks.json

springdoc:
  apiDocs:
    enabled: false
  swaggerUi:
    enabled: false
