auth:
  audience: http://localhost
  issuer: http://localhost

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - \${auth.audience}
              - http://localhost:3000
  data:
    redis:
      ssl:
        enabled: false

management:
  tracing:
    probability: 1.0
