info:
  app:
    organization: leijendary
    group: ${group}
    name: ${name}
    description: ${description}
    version: ${version}
  api:
    termsOfService:
    contact:
      name: Jonathan Leijendekker
      url: https://leijendary.com
      email:
    license:
      name: Jonathan Leijendekker
      url: https://leijendary.com

auth:
  audience: https://leijendary.com
  issuer: https://leijendary.com
  jwkSetUri:

request:
  maxSize: 100MB

retry:
  retries: 3
  backoff:
    firstBackoff: 5ms
    maxBackoff: 20ms
    factor: 2
    basedOnPreviousValue: true

spring:
  application:
    name: \${info.app.name}
  cloud:
    discovery:
      client:
        simple:
          instances:
            iam:
              - uri:
            notification:
              - uri:
            sample:
              - uri:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
      httpclient:
        connectTimeout: 60000
        responseTimeout: 1m
        wiretap: true
      httpserver:
        wiretap: true
      loadbalancer:
        use404: true
      redisRateLimiter:
        config:
          defaultFilters:
            replenishRate: 10
            burstCapacity: 20
            requestedTokens: 1
      routes:
        # Token
        - id: token-create-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/token
            - Method=POST
        - id: token-refresh-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/token/refresh
            - Method=POST
        - id: token-revoke-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/token
            - Method=DELETE
        - id: token-social-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/token/social
            - Method=POST

        # Register
        - id: register-email-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/register/email
            - Method=POST
        - id: register-phone-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/register/phone
            - Method=POST

        # Password
        - id: password-nominate-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/password
            - Method=POST
        - id: password-change-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/password
            - Method=PUT
          filters:
            - Authenticated
        - id: password-reset-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/password/reset
            - Method=POST

        # Profile
        - id: profile-get-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/profile
            - Method=GET
          filters:
            - Authenticated
        - id: profile-update-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/profile
            - Method=PUT
          filters:
            - Authenticated
        - id: profile-email-change-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/profile/email
            - Method=PATCH
          filters:
            - Authenticated
        - id: profile-phone-change-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/profile/phone
            - Method=PATCH
          filters:
            - Authenticated

        # Picture
        - id: picture-link-get-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/picture/link
            - Method=GET
          filters:
            - Authenticated
        - id: picture-link-put-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/picture/link
            - Method=PUT
          filters:
            - Authenticated

        # Address
        - id: address-list-v1
          uri: lb://iam
          order: 1
          predicates:
            - Path=/api/v1/addresses
            - Method=GET
          filters:
            - Authenticated
        - id: address-create-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/addresses
            - Method=POST
          filters:
            - Authenticated
        - id: address-get-v1
          uri: lb://iam
          order: 0
          predicates:
            - Path=/api/v1/addresses/{id}
            - Method=GET
          filters:
            - Authenticated
        - id: address-update-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/addresses/{id}
            - Method=PUT
          filters:
            - Authenticated
        - id: address-delete-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/addresses/{id}
            - Method=DELETE
          filters:
            - Authenticated

        # Role
        - id: role-list-v1
          uri: lb://iam
          order: 1
          predicates:
            - Path=/api/v1/roles
            - Method=GET
          filters:
            - Authenticated=urn:role:list:v1
        - id: role-create-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/roles
            - Method=POST
          filters:
            - Authenticated=urn:role:create:v1
        - id: role-get-v1
          uri: lb://iam
          order: 0
          predicates:
            - Path=/api/v1/roles/{id}
            - Method=GET
          filters:
            - Authenticated=urn:role:get:v1
        - id: role-update-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/roles/{id}
            - Method=PUT
          filters:
            - Authenticated=urn:role:update:v1
        - id: role-delete-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/roles/{id}
            - Method=DELETE
          filters:
            - Authenticated=urn:role:delete:v1

        # Role Permission
        - id: role-permission-list-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/roles/{roleId}/permissions
            - Method=GET
          filters:
            - Authenticated=urn:role:permission:list:v1
        - id: role-permission-add-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/roles/{roleId}/permissions
            - Method=POST
          filters:
            - Authenticated=urn:role:permission:add:v1
        - id: role-permission-remove-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/roles/{roleId}/permissions/{id}
            - Method=DELETE
          filters:
            - Authenticated=urn:role:permission:remove:v1

        # Permission
        - id: permission-list-v1
          uri: lb://iam
          order: 1
          predicates:
            - Path=/api/v1/permissions
            - Method=GET
          filters:
            - Authenticated=urn:permission:list:v1
        - id: permission-create-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/permissions
            - Method=POST
          filters:
            - Authenticated=urn:permission:create:v1
        - id: permission-get-v1
          uri: lb://iam
          order: 0
          predicates:
            - Path=/api/v1/permissions/{id}
            - Method=GET
          filters:
            - Authenticated=urn:permission:get:v1
        - id: permission-update-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/permissions/{id}
            - Method=PUT
          filters:
            - Authenticated=urn:permission:update:v1
        - id: permission-delete-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/permissions/{id}
            - Method=DELETE
          filters:
            - Authenticated=urn:permission:delete:v1

        # User
        - id: user-list-v1
          uri: lb://iam
          order: 1
          predicates:
            - Path=/api/v1/users
            - Method=GET
          filters:
            - Authenticated=urn:user:list:v1
        - id: user-create-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/users
            - Method=POST
          filters:
            - Authenticated=urn:user:create:v1
        - id: user-get-v1
          uri: lb://iam
          order: 0
          predicates:
            - Path=/api/v1/users/{id}
            - Method=GET
          filters:
            - Authenticated=urn:user:get:v1
        - id: user-update-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/users/{id}
            - Method=PUT
          filters:
            - Authenticated=urn:user:update:v1
        - id: user-delete-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/users/{id}
            - Method=DELETE
          filters:
            - Authenticated=urn:user:delete:v1

        # Verification
        - id: verification-create-v1
          uri: lb://iam
          predicates:
            - Path=/api/v1/verification
            - Method=POST

        # Device
        - id: device-register-v1
          uri: lb://notification
          predicates:
            - Path=/api/v1/devices
            - Method=POST
          filters:
            - Authenticated
        - id: device-deregister-v1
          uri: lb://notification
          predicates:
            - Path=/api/v1/devices
            - Method=DELETE
          filters:
            - Authenticated

        # Notification
        - id: notification-list-v1
          uri: lb://notification
          order: 1
          predicates:
            - Path=/api/v1/notifications
            - Method=GET
          filters:
            - Authenticated
        - id: notification-get-v1
          uri: lb://notification
          order: 0
          predicates:
            - Path=/api/v1/notifications/{id}
            - Method=GET
          filters:
            - Authenticated
        - id: notification-delete-v1
          uri: lb://notification
          predicates:
            - Path=/api/v1/notifications/{id}
            - Method=DELETE
          filters:
            - Authenticated

        # Sample
        - id: sample-list-v1
          uri: lb://sample
          order: 1
          predicates:
            - Path=/api/v1/samples
            - Method=GET
          filters:
            - Authenticated=urn:sample:list:v1
        - id: sample-create-v1
          uri: lb://sample
          predicates:
            - Path=/api/v1/samples
            - Method=POST
          filters:
            - Authenticated=urn:sample:create:v1
        - id: sample-get-v1
          uri: lb://sample
          order: 0
          predicates:
            - Path=/api/v1/samples/{id}
            - Method=GET
          filters:
            - Authenticated=urn:sample:get:v1
        - id: sample-update-v1
          uri: lb://sample
          predicates:
            - Path=/api/v1/samples/{id}
            - Method=PUT
          filters:
            - Authenticated=urn:sample:update:v1
        - id: sample-delete-v1
          uri: lb://sample
          predicates:
            - Path=/api/v1/samples/{id}
            - Method=DELETE
          filters:
            - Authenticated=urn:sample:delete:v1

    serviceRegistry:
      autoRegistration:
        enabled: false
  data:
    redis:
      host:
      port:
      ssl: true
      username:
      password:
  main:
    bannerMode: log
  messages:
    basename: messages.access, messages.error

server:
  error:
    whitelabel:
      enabled: false
  http2:
    enabled: true
  port: 80

management:
  endpoint:
    gateway:
      enabled: true
    health:
      showDetails: ALWAYS
  endpoints:
    web:
      exposure:
        include: health, gateway, prometheus
  zipkin:
    tracing:
      endpoint:

logging:
  pattern:
    level: '%5p [\${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
