apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: gateway
data:
  SPRING_REDIS_HOST: redis-service.cache.svc.cluster.local
  SPRING_REDIS_PORT: "6379"
  SPRING_CLOUD_DISCOVERY_CLIENT_SIMPLE_INSTANCES_SAMPLE_0_URI: http://spring-template-service.template.svc.cluster.local
