apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-api-gateway-config
  namespace: gateway
data:
  AUTH_AUDIENCE: http://localhost
  AUTH_JWK_SET_URI: http://spring-iam-template-service.template.svc.cluster.local/api/v1/.well-known/jwks.json
  SPRING_DATA_REDIS_HOST: redis-service.cache.svc.cluster.local
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_CLOUD_DISCOVERY_CLIENT_SIMPLE_INSTANCES_IAM_0_URI: http://spring-iam-template-service.template.svc.cluster.local
  SPRING_CLOUD_DISCOVERY_CLIENT_SIMPLE_INSTANCES_SAMPLE_0_URI: http://spring-template-service.template.svc.cluster.local
  MANAGEMENT_OTLP_METRICS_EXPORT_URL: http://jaeger-service.monitoring.svc.cluster.local:4318/v1/metrics
  MANAGEMENT_OTLP_TRACING_ENDPOINT: http://jaeger-service.monitoring.svc.cluster.local:4318/v1/traces
