apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: gateway
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: jleijendekker/api-gateway:1.0.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: api-gateway-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 70
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: 512M
              cpu: 0.25
            limits:
              memory: 512M
              cpu: 0.25

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: gateway
spec:
  selector:
    app: api-gateway
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
