apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api-gateway
  namespace: gateway
  labels:
    app: spring-api-gateway
spec:
  selector:
    matchLabels:
      app: spring-api-gateway
  template:
    metadata:
      labels:
        app: spring-api-gateway
    spec:
      containers:
        - name: spring-api-gateway
          image: jleijendekker/spring-api-gateway:1.0.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: spring-api-gateway-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: 1G
              cpu: 0.5
            limits:
              memory: 1G
              cpu: 0.5

---
apiVersion: v1
kind: Service
metadata:
  name: spring-api-gateway-service
  namespace: gateway
spec:
  selector:
    app: spring-api-gateway
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
