on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'zulu'
          cache: 'gradle'
      - name: Execute Gradle Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --info
        env:
          SPRING_PROFILES_ACTIVE: ci
    services:
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
      zipkin:
        image: openzipkin/zipkin:2
        ports:
          - 9411:9411
