on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Execute Gradle Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --info
        env:
          SPRING_PROFILES_ACTIVE: cicd
    services:
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
      jaeger:
        image: jaegertracing/all-in-one:1
        ports:
          - 5775:5775/udp
          - 6831:6831/udp
          - 6832:6832/udp
          - 5778:5778
          - 16686:16686
          - 14250:14250
          - 14268:14268
          - 14269:14269
          - 9411:9411
        env:
          COLLECTOR_ZIPKIN_HOST_PORT: :9411
